FROM openjdk:8
RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list
RUN sed -i 's@/archive.ubuntu.com/@/mirrors.aliyun.com/@g' /etc/apt/sources.list
RUN apt-get update; \
    apt-get install -y --no-install-recommends \
        net-tools \
    ; \
    rm -rf /var/lib/apt/lists/*

RUN echo "Asia/Shanghai" > /etc/timezone \
&& ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

VOLUME /tmp
COPY user-platform-starter-1.0.jar app.jar

ENTRYPOINT ["java","-jar","/app.jar"]
