server:
  port: 7333
spring:
  datasource:
    druid:
      username: virowin
      password: 123456
      url: jdbc:mysql://localhost:3306/user_platform?serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 20
      maxActive: 200
      minIdle: 20
      maxWait: 6000
  mail:
    host: localhost
    port: 465
    username: test@126.com
    password: test1
    protocol: smtps
    properties:
      mail:
        debug: false
        smtp:
          timeout: 5000
          ssl:
            enable: true
          socketFactory:
            port:
            class:
          auth: true
          starttls:
            enable: true
            required: true